export { type User } from './user.interface'
export { type LoginResponse, type RegisterResponse } from './auth.interface'
export { type Company } from './company.interface'
export { type NewCompany } from './newCompany.interface'
export type { Request, RequestResponse, Document, StatusRequest, Data } from './requests.interface'